-- Quizio private Content Studio: Supabase Auth owner allow-list and quiz content.

create table if not exists public.quizio_admins (
  email text primary key,
  created_at timestamptz not null default now()
);

insert into public.quizio_admins (email)
values ('aymenlasfar4@icloud.com')
on conflict (email) do nothing;

create or replace function public.is_quizio_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.quizio_admins
    where lower(email) = lower(coalesce(auth.jwt() ->> 'email', ''))
  );
$$;

grant execute on function public.is_quizio_admin() to anon, authenticated;

create table if not exists public.quiz_categories (
  id bigint generated by default as identity primary key,
  name text not null unique,
  slug text not null unique,
  icon text,
  color text,
  is_active boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.quiz_questions (
  id bigint generated by default as identity primary key,
  category_id bigint not null references public.quiz_categories(id) on delete restrict,
  prompt text not null check (char_length(trim(prompt)) between 1 and 500),
  option_a text not null check (char_length(trim(option_a)) between 1 and 300),
  option_b text not null check (char_length(trim(option_b)) between 1 and 300),
  option_c text not null check (char_length(trim(option_c)) between 1 and 300),
  option_d text not null check (char_length(trim(option_d)) between 1 and 300),
  correct_option_index smallint not null check (correct_option_index between 0 and 3),
  explanation text not null check (char_length(trim(explanation)) between 1 and 1000),
  difficulty text not null default 'medium' check (difficulty in ('easy', 'medium', 'hard')),
  status text not null default 'draft' check (status in ('draft', 'published', 'paused', 'archived')),
  source_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists quiz_questions_category_status_idx
  on public.quiz_questions (category_id, status);

create or replace function public.set_quizio_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists quiz_categories_set_updated_at on public.quiz_categories;
create trigger quiz_categories_set_updated_at
before update on public.quiz_categories
for each row execute procedure public.set_quizio_updated_at();

drop trigger if exists quiz_questions_set_updated_at on public.quiz_questions;
create trigger quiz_questions_set_updated_at
before update on public.quiz_questions
for each row execute procedure public.set_quizio_updated_at();

alter table public.quizio_admins enable row level security;
alter table public.quiz_categories enable row level security;
alter table public.quiz_questions enable row level security;

drop policy if exists "admins can read owner allow-list" on public.quizio_admins;
create policy "admins can read owner allow-list"
on public.quizio_admins for select to authenticated
using (public.is_quizio_admin());

drop policy if exists "published categories are readable" on public.quiz_categories;
create policy "published categories are readable"
on public.quiz_categories for select to anon, authenticated
using (is_active or public.is_quizio_admin());

drop policy if exists "admins manage categories" on public.quiz_categories;
create policy "admins manage categories"
on public.quiz_categories for all to authenticated
using (public.is_quizio_admin())
with check (public.is_quizio_admin());

drop policy if exists "published questions are readable" on public.quiz_questions;
create policy "published questions are readable"
on public.quiz_questions for select to anon, authenticated
using (status = 'published' or public.is_quizio_admin());

drop policy if exists "admins manage questions" on public.quiz_questions;
create policy "admins manage questions"
on public.quiz_questions for all to authenticated
using (public.is_quizio_admin())
with check (public.is_quizio_admin());

insert into public.quiz_categories (name, slug, icon, color, sort_order)
values
  ('Geography', 'geography', 'public', '#2563EB', 1),
  ('Science', 'science', 'science', '#0F9F9A', 2),
  ('History', 'history', 'account-balance', '#A855F7', 3),
  ('Nature', 'nature', 'eco', '#16A34A', 4)
on conflict (slug) do nothing;
